# Generated by Django 3.1.7 on 2021-03-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysource',
            name='desc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerysource',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
